### ISSUE TITLE
yarn command could not be found

### ISSUE THREAD

**Issue by josefglatz** [edbizarro/gitlab-ci-pipeline-php#44]
Hi,

is it possible, that something has changed since the last 3 days for `edbizarro/gitlab-ci-pipeline-php:7.2-alpine`?

![image](https://user-images.githubusercontent.com/2861556/44653191-52b98280-a9ee-11e8-8ba9-6b8e1250accf.png)

`yarn install` execution stops but `yarn cache clean` doesn't stop.

Seems like the new yarn version – which is shipped with the latest image is somewhat broken?

Works: 1.7.0
Breaks: 1.9.4

**Comment by edbizarro** [comment]
hi @josefglatz 

that's weird, I've pushed some changes to alpine images today, let me know if this still happening

**Comment by vkemeter** [comment]
hi @edbizarro, 

unfortunately the problem still exists.

![image](https://user-images.githubusercontent.com/1773048/44702089-f14aef80-aa91-11e8-98c6-28fd96d97118.png)

what i do not understand is, that yarn seems to work first (yarn config, yarn cache clean) - but a yarn install fails then due to "not finding yarn" in specific place.

**Comment by vkemeter** [comment]
small update:

i removed the `yarn cache clean` cmd and then everything works as expected.
